require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShopsController do

  before (:each) do
    @user = Factory(:user)
    sign_in @user
  end

  def valid_attributes
    { 
      :name => "OWW SFF",
      :points_to_submit => 4,
    }
  end

  describe "GET index" do
    it "assigns all shops as @shops" do
      shop = Shop.create! valid_attributes
      get :index
      assigns(:shops).should eq([shop])
    end
  end

  describe "GET show" do
    it "assigns the requested shop as @shop" do
      shop = Shop.create! valid_attributes
      get :show, :id => shop.id.to_s
      assigns(:shop).should eq(shop)
    end
  end

  describe "GET new" do
    it "assigns a new shop as @shop" do
      get :new
      assigns(:shop).should be_a_new(Shop)
    end
  end

  describe "GET edit" do
    it "assigns the requested shop as @shop" do
      shop = Shop.create! valid_attributes
      get :edit, :id => shop.id.to_s
      assigns(:shop).should eq(shop)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shop" do
        expect {
          post :create, :shop => valid_attributes
        }.to change(Shop, :count).by(1)
      end

      it "assigns a newly created shop as @shop" do
        post :create, :shop => valid_attributes
        assigns(:shop).should be_a(Shop)
        assigns(:shop).should be_persisted
      end

      it "redirects to the created shop" do
        post :create, :shop => valid_attributes
        response.should redirect_to(Shop.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shop as @shop" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shop.any_instance.stub(:save).and_return(false)
        post :create, :shop => {}
        assigns(:shop).should be_a_new(Shop)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shop.any_instance.stub(:save).and_return(false)
        post :create, :shop => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shop" do
        shop = Shop.create! valid_attributes
        # Assuming there are no other shops in the database, this
        # specifies that the Shop created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shop.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => shop.id, :shop => {'these' => 'params'}
      end

      it "assigns the requested shop as @shop" do
        shop = Shop.create! valid_attributes
        put :update, :id => shop.id, :shop => valid_attributes
        assigns(:shop).should eq(shop)
      end

      it "redirects to the shop" do
        shop = Shop.create! valid_attributes
        put :update, :id => shop.id, :shop => valid_attributes
        response.should redirect_to(shop)
      end
    end

    describe "with invalid params" do
      it "assigns the shop as @shop" do
        shop = Shop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shop.any_instance.stub(:save).and_return(false)
        put :update, :id => shop.id.to_s, :shop => {}
        assigns(:shop).should eq(shop)
      end

      it "re-renders the 'edit' template" do
        shop = Shop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shop.any_instance.stub(:save).and_return(false)
        put :update, :id => shop.id.to_s, :shop => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shop" do
      shop = Shop.create! valid_attributes
      expect {
        delete :destroy, :id => shop.id.to_s
      }.to change(Shop, :count).by(-1)
    end

    it "redirects to the shops list" do
      shop = Shop.create! valid_attributes
      delete :destroy, :id => shop.id.to_s
      response.should redirect_to(shops_url)
    end
  end

end
